# fly.toml app configuration file generated for openchess on 2026-07-09T23:22:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openchess'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  BIND = '0.0.0.0:8080'
  SIWE_CHAIN_ID = '8453'
  SIWE_DOMAIN = 'openchess-five.vercel.app'
  WEB_ORIGIN = 'https://openchess-five.vercel.app'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '3s'
    grace_period = '10s'
    method = 'get'
    path = '/ready'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
