// The repertoire layer: which built-in opening books exist, how a user's
// four-slot repertoire is assembled from them, and lazy loading.
//
// A repertoire has two halves — what you open with as White, and what you
// answer with as Black — so it is four slots, not one book. Assembling it is
// literally concatenation: Polyglot is keyed by position, and each built-in
// book only stores the moves of the side that owns it (see
// public/books/BOOKS.md), so a White entry can never match a Black-to-move
// position. `pnpm test:books` pins that property.
//
// This is where a bot's identity mostly comes from, and unlike search tweaks it
// costs no strength — playing the Najdorf every game is established theory, not
// a worse move.

import { parseBook, type BookEntry, type BookPick } from "./polyglot";

export type BookSlot = "white" | "vsE4" | "vsD4" | "vsOther";
/** The six playing styles. Every style exists in every slot, so a repertoire
 *  can be pure (all Sharp) or mixed (Sharp as White, Solid as Black). */
export type BookStyle = "classical" | "sharp" | "solid" | "hypermodern" | "gambit" | "offbeat";

export type BookMeta = {
  id: string;
  label: string;
  slot: BookSlot;
  style: BookStyle;
  /** Transfer size, shown in the picker so a choice never surprises. */
  bytes: number;
};

/** The built-in books, generated by `pnpm build:books` from CC0 PGN.
 *  Organized by STYLE × SLOT, not by first move — "sharp" is a weighted mix of
 *  the Open Sicilian, King's Gambit, Vienna and the Advance variations, not one
 *  defence. Keep `bytes` in step with public/books/*.bin when rebuilding. */
export const BOOKS: BookMeta[] = [
  { id: "w-classical", label: "Classical — main lines", slot: "white", style: "classical", bytes: 153056 },
  { id: "w-sharp", label: "Sharp — open lines, initiative", slot: "white", style: "sharp", bytes: 66496 },
  { id: "w-solid", label: "Solid — structure first", slot: "white", style: "solid", bytes: 106656 },
  { id: "w-hypermodern", label: "Hypermodern — flank pressure", slot: "white", style: "hypermodern", bytes: 111712 },
  { id: "w-gambit", label: "Gambiteer — pawns for time", slot: "white", style: "gambit", bytes: 105504 },
  { id: "w-offbeat", label: "Offbeat — off the map", slot: "white", style: "offbeat", bytes: 22000 },

  { id: "b-e4-classical", label: "Classical — 1…e5", slot: "vsE4", style: "classical", bytes: 30912 },
  { id: "b-e4-sharp", label: "Sharp — Sicilian & Winawer", slot: "vsE4", style: "sharp", bytes: 62336 },
  { id: "b-e4-solid", label: "Solid — Caro-Kann & Petroff", slot: "vsE4", style: "solid", bytes: 31904 },
  { id: "b-e4-hypermodern", label: "Hypermodern — Pirc & Modern", slot: "vsE4", style: "hypermodern", bytes: 12560 },
  { id: "b-e4-gambit", label: "Gambiteer — counter-gambits", slot: "vsE4", style: "gambit", bytes: 13584 },
  { id: "b-e4-offbeat", label: "Offbeat — Scandi & friends", slot: "vsE4", style: "offbeat", bytes: 10208 },

  { id: "b-d4-classical", label: "Classical — QGD & Nimzo", slot: "vsD4", style: "classical", bytes: 26064 },
  { id: "b-d4-sharp", label: "Sharp — KID, Grünfeld, Dutch", slot: "vsD4", style: "sharp", bytes: 13888 },
  { id: "b-d4-solid", label: "Solid — Slav & Queen's Indian", slot: "vsD4", style: "solid", bytes: 22400 },
  { id: "b-d4-hypermodern", label: "Hypermodern — Indian defences", slot: "vsD4", style: "hypermodern", bytes: 21408 },
  { id: "b-d4-gambit", label: "Gambiteer — Budapest & Benko", slot: "vsD4", style: "gambit", bytes: 9248 },
  { id: "b-d4-offbeat", label: "Offbeat — Dutch & QGA", slot: "vsD4", style: "offbeat", bytes: 21392 },

  { id: "b-other-classical", label: "Classical — …e5 & …Nf6", slot: "vsOther", style: "classical", bytes: 45920 },
  { id: "b-other-sharp", label: "Sharp — Reversed Sicilian", slot: "vsOther", style: "sharp", bytes: 38384 },
  { id: "b-other-solid", label: "Solid — …d5 & Symmetrical", slot: "vsOther", style: "solid", bytes: 25392 },
  { id: "b-other-hypermodern", label: "Hypermodern — …Nf6", slot: "vsOther", style: "hypermodern", bytes: 33792 },
  { id: "b-other-gambit", label: "Gambiteer — sharpest reply", slot: "vsOther", style: "gambit", bytes: 22256 },
  { id: "b-other-offbeat", label: "Offbeat — Symmetrical & …d5", slot: "vsOther", style: "offbeat", bytes: 44688 },
];

const BY_ID = new Map(BOOKS.map((b) => [b.id, b]));

export function booksForSlot(slot: BookSlot): BookMeta[] {
  return BOOKS.filter((b) => b.slot === slot);
}

/** `null` in a slot means "no book here — play the engine from move one". */
export type Repertoire = {
  white: string | null;
  vsE4: string | null;
  vsD4: string | null;
  vsOther: string | null;
  /** Leave book after this many plies. */
  maxPly: number;
  /** `best` replays the same game every time; `weighted` varies within theory. */
  pick: BookPick;
};

export const DEFAULT_REPERTOIRE: Repertoire = {
  white: null,
  vsE4: null,
  vsD4: null,
  vsOther: null,
  maxPly: 16,
  pick: "weighted",
};

export const SLOTS: { slot: BookSlot; label: string }[] = [
  { slot: "white", label: "As White, I open with" },
  { slot: "vsE4", label: "As Black, vs 1.e4" },
  { slot: "vsD4", label: "As Black, vs 1.d4" },
  { slot: "vsOther", label: "As Black, vs anything else" },
];

const STYLE_BLURBS: Record<BookStyle, string> = {
  classical: "Main lines with both colours — Ruy Lopez, Queen's Gambit, Nimzo-Indian.",
  sharp: "Open Sicilians, the King's Gambit, the King's Indian. Unbalanced on purpose.",
  solid: "Rossolimo, Caro-Kann, Slav. Structure first; hard to knock over.",
  hypermodern: "English, Réti, Indian defences — cede the centre, then attack it.",
  gambit: "Pawns for time: King's Gambit, Smith-Morra, Budapest, Benko.",
  offbeat: "1.b3, 1.f4, the Dutch, the Scandinavian. Off the beaten path.",
};

const STYLE_LABELS: Record<BookStyle, string> = {
  classical: "Classical",
  sharp: "Sharp",
  solid: "Solid",
  hypermodern: "Hypermodern",
  gambit: "Gambiteer",
  offbeat: "Offbeat",
};

export const STYLES = Object.keys(STYLE_LABELS) as BookStyle[];

/** Named starting points that fill all four slots with one style. Every slot
 *  stays individually editable afterward — a preset is a shortcut, not a mode,
 *  and mixing (Sharp as White, Solid as Black) is a first-class option. */
export const PRESETS: { id: BookStyle; label: string; blurb: string; rep: Omit<Repertoire, "maxPly" | "pick"> }[] =
  STYLES.map((style) => ({
    id: style,
    label: STYLE_LABELS[style],
    blurb: STYLE_BLURBS[style],
    rep: {
      white: BOOKS.find((b) => b.slot === "white" && b.style === style)?.id ?? null,
      vsE4: BOOKS.find((b) => b.slot === "vsE4" && b.style === style)?.id ?? null,
      vsD4: BOOKS.find((b) => b.slot === "vsD4" && b.style === style)?.id ?? null,
      vsOther: BOOKS.find((b) => b.slot === "vsOther" && b.style === style)?.id ?? null,
    },
  }));

/** Validate a repertoire read from localStorage. Unknown ids become `null`
 *  rather than a 404 fetch mid-game, and every number is clamped — this blob
 *  is user-editable and feeds the move loop. */
export function normalizeRepertoire(raw: unknown): Repertoire {
  const r = (raw ?? {}) as Partial<Record<keyof Repertoire, unknown>>;
  const slot = (v: unknown, s: BookSlot): string | null =>
    typeof v === "string" && BY_ID.get(v)?.slot === s ? v : null;
  const maxPly = Number(r.maxPly);
  return {
    white: slot(r.white, "white"),
    vsE4: slot(r.vsE4, "vsE4"),
    vsD4: slot(r.vsD4, "vsD4"),
    vsOther: slot(r.vsOther, "vsOther"),
    maxPly: Number.isFinite(maxPly) ? Math.min(60, Math.max(0, Math.round(maxPly))) : DEFAULT_REPERTOIRE.maxPly,
    pick: r.pick === "best" ? "best" : "weighted",
  };
}

export function selectedBookIds(rep: Repertoire): string[] {
  return [rep.white, rep.vsE4, rep.vsD4, rep.vsOther].filter((id): id is string => id !== null);
}

/** Short human label — "Sharp", or "Sharp/Solid" for a mixed repertoire. Used
 *  for the engine string declared to opponents, which the server caps at 48
 *  chars, so it names styles rather than listing four book titles. */
export function repertoireLabel(rep: Repertoire): string {
  const styles = selectedBookIds(rep)
    .map((id) => BY_ID.get(id)?.style)
    .filter((s): s is BookStyle => !!s);
  if (styles.length === 0) return "";
  const unique = [...new Set(styles)];
  if (unique.length === 1) return STYLE_LABELS[unique[0]];
  // Mixed: name White's style and Black's dominant one, which is what an
  // opponent actually cares about.
  const whiteStyle = rep.white ? BY_ID.get(rep.white)?.style : undefined;
  const rest = unique.filter((s) => s !== whiteStyle);
  return [whiteStyle, rest[0]].filter(Boolean).map((s) => STYLE_LABELS[s as BookStyle]).join("/");
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/** Concatenate books into one probeable set.
 *
 *  The sort is load-bearing, not tidiness: `entriesFor` binary-searches, so
 *  concatenating two individually-sorted books without re-sorting would make
 *  most positions un-findable. */
export function concatBooks(books: BookEntry[][]): BookEntry[] {
  const all = books.flat();
  all.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  return all;
}

const cache = new Map<string, Promise<BookEntry[]>>();

/** Fetch + parse one built-in book, memoized per session. A failed fetch is
 *  evicted so a transient error doesn't poison the slot for the whole session. */
export function loadBook(id: string): Promise<BookEntry[]> {
  const hit = cache.get(id);
  if (hit) return hit;
  const p = fetch(`/books/${id}.bin`)
    .then((r) => {
      if (!r.ok) throw new Error(`book ${id}: HTTP ${r.status}`);
      return r.arrayBuffer();
    })
    .then(parseBook)
    .catch((e) => {
      cache.delete(id);
      throw e;
    });
  cache.set(id, p);
  return p;
}

/** Load every book in a repertoire and merge them into one probeable set.
 *  Resolves to an empty array for an all-empty repertoire. */
export async function loadRepertoire(rep: Repertoire): Promise<BookEntry[]> {
  const ids = selectedBookIds(rep);
  if (ids.length === 0) return [];
  return concatBooks(await Promise.all(ids.map(loadBook)));
}
